# Generated by Django 4.2.6 on 2023-10-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion_estimada', models.DateField()),
            ],
        ),
    ]
